import { graphql } from "../../generated";

export const AccountListQueryDocument = graphql(`
  query AccountList($filter: AccountFilter, $after: Cursor, $first: Int, $orderBy: [AccountsOrderBy!]) {
    allAccounts(filter: $filter, after: $after, first: $first, orderBy: $orderBy) {
      __typename
      totalCount
      pageInfo {
        hasNextPage
        hasPreviousPage
        startCursor
        endCursor
      }
      nodes {
        accountName
        billingAddress
        shippingAddress
        city
        state
        postalCode
        country
        annualRevenue
        numberOfEmployees
        ownership
        parentAccountId
        id
        accountSource
        description
        createdDate
        lastModifiedDate
        lastActivityDate
        rating
        sicCode
        tickerSymbol
        ownershipType
        accountType
        createdAt
        territory
        marketSegment
        primaryContactName
        primaryContactEmail
        primaryContactPhone
        secondaryContactName
        secondaryContactEmail
        secondaryContactPhone
        accountManagerId
        accountManagerId
        accountManagerName
        accountManagerEmail
        accountManagerPhone
        updatedAt
        renewalDate
        contractStartDate
        contractEndDate
        subscriptionType
        paymentTerms
        lastPurchaseDate
        totalPurchaseValue
        openOpportunities
        closedOpportunities
        activeContracts
        inactiveContracts
        isPartner
        isCustomer
        isProspect
        industryVertical
        referralSource
        marketingBudget
        leadSource
        accountNumber
        businessUnit
        accountStatus
        upsellOpportunities
        crossSellOpportunities
        competitor
        accountTier
        lastContactedDate
        customerSince
        loyaltyScore
        npsScore
        industry
        accountRegion
        preferredContactMethod
        renewalProbability
        strategicAccount
        socialMediaHandle
        preferredLanguage
        timezone
        annualSpend
        engagementScore
        website
        phoneNumber
        email
        usersByAccountId {
          totalCount
          nodes {
            phoneNumber
            dateOfBirth
            gender
            jobTitle
            jobTitle
            department
            isActive
            isVerified
            lastLoginDate
            profileImageUrl
            id
            firstName
            lastName
            email
          }
        }
        opportunitiesByAccountId {
          totalCount
          nodes {
            id
            createdAt
            updatedAt
            opportunityName
            source
            closeDate
            stage
            probability
            status
            userByOwnerId {
              id
              lastName
              firstName
              email
            }
          }
        }
      }
    }
  }
`);

export const AccountDataLoaders = graphql(`
  query AccountListForLoaders($filter: AccountFilter, $after: Cursor, $first: Int, $orderBy: [AccountsOrderBy!]) {
    data: allAccounts(filter: $filter, after: $after, first: $first, orderBy: $orderBy) {
      __typename
      totalCount
      pageInfo {
        hasNextPage
        hasPreviousPage
        startCursor
        endCursor
      }
      nodes {
        accountName
        billingAddress
        shippingAddress
        city
        state
        postalCode
        country
        annualRevenue
        numberOfEmployees
        ownership
        parentAccountId
        id
        accountSource
        description
        createdDate
        lastModifiedDate
        lastActivityDate
        rating
        sicCode
        tickerSymbol
        ownershipType
        accountType
        createdAt
        territory
        marketSegment
        primaryContactName
        primaryContactEmail
        primaryContactPhone
        secondaryContactName
        secondaryContactEmail
        secondaryContactPhone
        accountManagerId
        accountManagerId
        accountManagerName
        accountManagerEmail
        accountManagerPhone
        updatedAt
        renewalDate
        contractStartDate
        contractEndDate
        subscriptionType
        paymentTerms
        lastPurchaseDate
        totalPurchaseValue
        openOpportunities
        closedOpportunities
        activeContracts
        inactiveContracts
        isPartner
        isCustomer
        isProspect
        industryVertical
        referralSource
        marketingBudget
        leadSource
        accountNumber
        businessUnit
        accountStatus
        upsellOpportunities
        crossSellOpportunities
        competitor
        accountTier
        lastContactedDate
        customerSince
        loyaltyScore
        npsScore
        industry
        accountRegion
        preferredContactMethod
        renewalProbability
        strategicAccount
        socialMediaHandle
        preferredLanguage
        timezone
        annualSpend
        engagementScore
        website
        phoneNumber
        email
      }
    }
  }
`);
